//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Payment.Api.Resources.ErrorMessagesResources", typeof(ErrorMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number can not be null or empty.
        /// </summary>
        public static string CardNumberCanNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CardNumberCanNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be numeric with 15-16 length.
        /// </summary>
        public static string CardNumberMustBeNumericWith15_16Length {
            get {
                return ResourceManager.GetString("CardNumberMustBeNumericWith15_16Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner information can not be null or empty.
        /// </summary>
        public static string CardOwnerCanNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CardOwnerCanNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Owner is invalid.
        /// </summary>
        public static string CardOwnerInvalid {
            get {
                return ResourceManager.GetString("CardOwnerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner information must be alphabetic.
        /// </summary>
        public static string CardOwnerMustBeAlphabetic {
            get {
                return ResourceManager.GetString("CardOwnerMustBeAlphabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number is invalid.
        /// </summary>
        public static string CreditCardNumberInvalid {
            get {
                return ResourceManager.GetString("CreditCardNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only American Express, Visa, or Mastercard cards accepted.
        /// </summary>
        public static string CreditCardOnlyAcceptedCards {
            get {
                return ResourceManager.GetString("CreditCardOnlyAcceptedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Type is invalid. Only accepted Amex, Mastercard and Visa.
        /// </summary>
        public static string CreditCardTypeInvalid {
            get {
                return ResourceManager.GetString("CreditCardTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC can not be null or empty.
        /// </summary>
        public static string CVCCanNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CVCCanNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC information is invalid.
        /// </summary>
        public static string CVCInvalid {
            get {
                return ResourceManager.GetString("CVCInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC must be numeric with 3-4 length.
        /// </summary>
        public static string CVCMustBeNumericWith3_4Length {
            get {
                return ResourceManager.GetString("CVCMustBeNumericWith3_4Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date can not be null or empty.
        /// </summary>
        public static string ExpirationDateCanNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ExpirationDateCanNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date must be MM/YY format.
        /// </summary>
        public static string ExpirationDateMustBeMMYYFormat {
            get {
                return ResourceManager.GetString("ExpirationDateMustBeMMYYFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date is invalid.
        /// </summary>
        public static string IssueDateInvalid {
            get {
                return ResourceManager.GetString("IssueDateInvalid", resourceCulture);
            }
        }
    }
}
